name: markdown-autodocs

on:
  push:
    paths:
      - 'lovelace/button_card_templates/**'
      - 'lovelace/button_card_templates_examples/**'
      - 'README.md'

jobs:        
  auto-update-readme:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Markdown autodocs
          uses: dineshsonachalam/markdown-autodocs@v1.0.4
          with:
            output_file_paths: '[./README.md]'
